name: Build and deploy Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: bazar
  PYTHON_VERSION: '3.11'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout: Clona el código del repositorio
      - uses: actions/checkout@v4

      # 2. Set up Python version: Configura Python 3.11 en el entorno de ejecución
      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      # 3. Create and start virtual environment: Crea y activa un entorno virtual
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # 4. Install dependencies: Instala las dependencias listadas en requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt

      # (Opcional) Agregar paso para ejecutar pruebas unitarias (usando PyTest, Django, etc.)

      # 5. Upload artifact for deployment jobs: Subir artefactos que serán usados en el trabajo de despliegue
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # 6. Download artifact from build job: Descargar los artefactos generados en el trabajo de construcción
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: .

      # 7. Deploy to Azure Web App: Despliega la aplicación en el Azure Web App especificado
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}